CREATE TABLE books(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    publisher VARCHAR(100),
    publidate DATE NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    CONSTRAINT price_no_negative check ( price >= 0 ),
    author_id BIGINT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES authors(id)

);